### ISSUE TITLE
module.symvers build error

### ISSUE THREAD

**Issue by carlosgonz0** [MorseMicro/morse_driver#1]
Hi
I not sure how to tackle this. maybe it need Morse configs enablements on Linux build ?

xxx@xxx:~/Documents/morse_driver-1.12.4$ make KERNEL_SRC=/usr/src/linux-headers-$(uname -r) CONFIG_WLAN_VENDOR_MORSE=m CONFIG_MORSE_SDIO=y CONFIG_MORSE_USER_ACCESS=y  
make MORSE_VERSION="0-rel_1_12_4_2024_Jun_11-6-g63cd0768" -C /usr/src/linux-headers-6.6.0-1 M=/home/Documents/morse_driver-1.12.4
make[1]: se entra en el directorio '/usr/src/linux-headers-6.6.0-1'
warning: the compiler differs from the one used to build the kernel
  The kernel was built by: aarch64-linux-gnu-gcc (Debian 10.2.1-6) 10.2.1 20210110
  You are using:           gcc (Debian 10.2.1-6) 10.2.1 20210110
  CC [M]  /home/Documents/morse_driver-1.12.4/dot11ah/main.o
  CC [M]  /home/Documents/morse_driver-1.12.4/dot11ah/debug.o
  CC [M]  /home/Documents/morse_driver-1.12.4/dot11ah/tx_11n_to_s1g.o
  CC [M]  /home/Documents/morse_driver-1.12.4/dot11ah/rx_s1g_to_11n.o
  CC [M]  /home/Documents/morse_driver-1.12.4/dot11ah/ie.o
  CC [M]  /home/Documents/morse_driver-1.12.4/dot11ah/tim.o
  CC [M]  /home/Documents/morse_driver-1.12.4/dot11ah/reg.o
  CC [M]  /home/Documents/morse_driver-1.12.4/dot11ah/s1g_ieee80211.o
  CC [M]  /home/Documents/morse_driver-1.12.4/dot11ah/s1g_channels.o
  LD [M]  /home/Documents/morse_driver-1.12.4/dot11ah/dot11ah.o
  CC [M]  /home/Documents/morse_driver-1.12.4/mac.o
  CC [M]  /home/Documents/morse_driver-1.12.4/init.o
  CC [M]  /home/Documents/morse_driver-1.12.4/skbq.o
  CC [M]  /home/Documents/morse_driver-1.12.4/debug.o
  CC [M]  /home/Documents/morse_driver-1.12.4/trace.o
  CC [M]  /home/Documents/morse_driver-1.12.4/mm6108.o
  CC [M]  /home/Documents/morse_driver-1.12.4/command.o
  CC [M]  /home/Documents/morse_driver-1.12.4/hw.o
  CC [M]  /home/Documents/morse_driver-1.12.4/beacon.o
  CC [M]  /home/Documents/morse_driver-1.12.4/pager_if.o
  CC [M]  /home/Documents/morse_driver-1.12.4/pageset.o
  CC [M]  /home/Documents/morse_driver-1.12.4/ps.o
  CC [M]  /home/Documents/morse_driver-1.12.4/raw.o
  CC [M]  /home/Documents/morse_driver-1.12.4/twt.o
  CC [M]  /home/Documents/morse_driver-1.12.4/cac.o
  CC [M]  /home/Documents/morse_driver-1.12.4/ndpprobe.o
  CC [M]  /home/Documents/morse_driver-1.12.4/of.o
  CC [M]  /home/Documents/morse_driver-1.12.4/firmware.o
  CC [M]  /home/Documents/morse_driver-1.12.4/pager_if_hw.o
  CC [M]  /home/Documents/morse_driver-1.12.4/pager_if_sw.o
  CC [M]  /home/Documents/morse_driver-1.12.4/watchdog.o
  CC [M]  /home/Documents/morse_driver-1.12.4/event.o
  CC [M]  /home/Documents/morse_driver-1.12.4/crc16_xmodem.o
  CC [M]  /home/Documents/morse_driver-1.12.4/offload.o
  CC [M]  /home/Documents/morse_driver-1.12.4/vendor_ie.o
  CC [M]  /home/Documents/morse_driver-1.12.4/bus_test.o
  CC [M]  /home/Documents/morse_driver-1.12.4/wiphy.o
  CC [M]  /home/Documents/morse_driver-1.12.4/ocs.o
  CC [M]  /home/Documents/morse_driver-1.12.4/mbssid.o
  CC [M]  /home/Documents/morse_driver-1.12.4/mesh.o
  CC [M]  /home/Documents/morse_driver-1.12.4/page_slicing.o
  CC [M]  /home/Documents/morse_driver-1.12.4/pv1.o
  CC [M]  /home/Documents/morse_driver-1.12.4/hw_scan.o
  CC [M]  /home/Documents/morse_driver-1.12.4/coredump.o
  CC [M]  /home/Documents/morse_driver-1.12.4/sdio.o
  CC [M]  /home/Documents/morse_driver-1.12.4/uaccess.o
  CC [M]  /home/Documents/morse_driver-1.12.4/minstrel_rc.o
  LD [M]  /home/Documents/morse_driver-1.12.4/morse.o
  MODPOST /home/Documents/morse_driver-1.12.4/Module.symvers
ERROR: modpost: "morse_vendor_send_mgmt_vendor_ie_found_event" [/home/Documents/morse_driver-1.12.4/morse.ko] undefined!
ERROR: modpost: "morse_vendor_reset_sta_transient_info" [/home/Documents/morse_driver-1.12.4/morse.ko] undefined!
ERROR: modpost: "morse_vendor_rx_caps_ops_ie" [/home/Documents/morse_driver-1.12.4/morse.ko] undefined!
ERROR: modpost: "morse_vendor_update_ack_timeout_on_assoc" [/home/Documents/morse_driver-1.12.4/morse.ko] undefined!
ERROR: modpost: "morse_vendor_insert_caps_ops_ie" [/home/Documents/morse_driver-1.12.4/morse.ko] undefined!
ERROR: modpost: "morse_vendor_send_ocs_done_event" [/home/Documents/morse_driver-1.12.4/morse.ko] undefined!
ERROR: modpost: "morse_vendor_send_peer_addr_event" [/home/Documents/morse_driver-1.12.4/morse.ko] undefined!
make[3]: [scripts/Makefile.modpost:145: /home/Documents/morse_driver-1.12.4/Module.symvers] Error 1 (no tiene efecto)
make[3]: *** No hay ninguna regla para construir el objetivo '/home/Documents/morse_driver-1.12.4/morse.ko', necesario para '__modfinal'.  Alto.
make[2]: [/usr/src/linux-headers-6.6.0-1/Makefile:1854: modules] Error 2 (no tiene efecto)
make[1]: se sale del directorio '/usr/src/linux-headers-6.6.0-1

**Comment by carlosgonz0** [comment]
Ok Looks like it need Morse configs enablements on Linux  build defconfigs

**Comment by AleTinti** [comment]
I encountered the same error a few days ago and managed to resolve it by adding the `CONFIG_MORSE_VENDOR_COMMAND=y` option to the build command.
I'm not 100% sure this is the correct solution, as I'm still working on getting the AsiaRF module fully functional, but this allowed me to successfully compile the dot11ah.ko and morse.ko modules.
I hope this can helps!

**Comment by carlosgonz0** [comment]
Hi AleTinti
adding: CONFIG_MORSE_VENDOR_COMMAND=y  fixed build here too.
Thank you so so so much. :pray:

**Comment by carlosgonz0** [comment]
Hi @s09289728096 

Any recommends for building morse driver? like Linux version support, Compiler version or Enablements defconfigs on Linux?

Thanks of advance.

**Comment by s09289728096** [comment]
> Hi @s09289728096 thanks for support.
> 
> Any recommends for building morse driver? like Linux version support, Compiler version or Enablements defconfigs on Linux?
> 
> Thanks of advance.

Generally the error about Unknown symbol occurs when you probe morse driver before installing dot11ah.ko. If it doesn't work, I can provide more help if you can show the system log for it.

**Comment by carlosgonz0** [comment]
>You can also try depmod the morse.ko and dot11ah.ko after putting them in /lib/modules/<what_kernel_you_are_using>/ folders if your linux distribution supports it. It should allow the modprobe command to automatically install all modules that morse.ko needs, such as mac80211 and cfg80211.

Hi
Only modprobe option fixed for"Unknown symbol" error by fixing module dep to load. So morse and dot11ah.ko has been loaded.
Thank you very much @s09289728096 :pray:

**Comment by carlosgonz0** [comment]
@s09289728096 before closing this bug, i still curious why adding: CONFIG_MORSE_VENDOR_COMMAND=y is fixing build morse driver as below issue.?

> MODPOST /home/Documents/morse_driver-1.12.4/Module.symvers
ERROR: modpost: "morse_vendor_send_mgmt_vendor_ie_found_event" [/home

**Comment by AleTinti** [comment]
> @s09289728096 before closing this bug, i still curious why adding: CONFIG_MORSE_VENDOR_COMMAND=y is fixing building morse driver as below issue.?
> 
> > MODPOST /home/Documents/morse_driver-1.12.4/Module.symvers
> > ERROR: modpost: "morse_vendor_send_mgmt_vendor_ie_found_event" [/home

While investigating where the functions reported in the error are defined, I found them in the `vendor.c` file. The corresponding object file is included only if the `CONFIG_MORSE_VENDOR_COMMAND=y` configuration is set in the Makefile. This is specified by the following directive:

```Makefile
morse-$(CONFIG_MORSE_VENDOR_COMMAND) += vendor.o

**Comment by AleTinti** [comment]
I correct myself: the definition of `CONFIG_MORSE_VENDOR_COMMAND` and other configurations can be found in the `Kconfig` file:

```Kconfig
config MORSE_VENDOR_COMMAND
	bool "Morse vendor commands"
	default n
	help
	  Allow vendor-specific commands from userspace applications such as iw.
```

**Comment by s09289728096** [comment]
> > @s09289728096 before closing this bug, i still curious why adding: CONFIG_MORSE_VENDOR_COMMAND=y is fixing building morse driver as below issue.?
> > > MODPOST /home/Documents/morse_driver-1.12.4/Module.symvers
> > > ERROR: modpost: "morse_vendor_send_mgmt_vendor_ie_found_event" [/home
> 
> While investigating where the functions reported in the error are defined, I found them in the `vendor.c` file. The corresponding object file is included only if the `CONFIG_MORSE_VENDOR_COMMAND=y` configuration is set in the Makefile. This is specified by the following directive:
> 
> ```makefile
> morse-$(CONFIG_MORSE_VENDOR_COMMAND) += vendor.o
> ```
> 
> Unfortunately, we do not have complete documentation to fully understand what each of these configurations does.

MORSE_VENDOR_COMMAND allows wireless to carry vendor information element. This configuration is default on in the openwrt sdk from morse micro. (see [here](https://github.com/MorseMicro/openwrt/blob/mm/v23.05.3/boards/common/morse_diffconfig))
The driver call functions in vendor.c everywhere, so vendor.o should be built in driver in default. Thus, CONFIG_MORSE_VENDOR_COMMAND=y is necessary.

**Comment by carlosgonz0** [comment]
Thank you both for all the help.  AleTinti, Elwin Huang.
